### ISSUE TITLE
Launcher segfaults if invalid global configuration parameter is referenced

### ISSUE THREAD

**Issue by hamishguthrie** [kmarkus/microblx#20]
This is easiest to explain by example. I have a block which I modified and removed a configuration parameter cw_offset, however in the configuration file, I still had a reference to a global variable, i.e. in the configuration I have `cw_offset = "&cw_offset",` the launcher segfaults without any error message. If I change the reference to a string value, i.e. `cw_offset = "offset_nrt",` I get the error message `set_config: unknown config 'cw_offset'` as expected.

**Comment by kmarkus** [comment]
Fixed in d8efc4190e9b92cb636368648bb29b57c01fc763, thanks for reporting!
