### ISSUE TITLE
error in running tests in freshly installed microblx 0.9

### ISSUE THREAD

**Issue by gborghesan** [kmarkus/microblx#26]
Hello all,
When I run tests in a freshly 0.9 compiled version, I get this error.

```
gborghesan@kul-XPS-15-9570:~/temp/microblx (master)$ ./run_tests.sh
running tests/test_block_composition.lua
luajit: /usr/share/lua/5.1/luaunit.lua:2013: assign to undeclared variable 'testNames'
stack traceback:
	[C]: in function 'error'
	/home/gborghesan/temp/uutils/lua/strict.lua:23: in function '__newindex'
	/usr/share/lua/5.1/luaunit.lua:2013: in function 'run'
	tests/test_block_composition.lua:385: in main chunk
	[C]: at 0x004044a0
```

I had also some problems in compiling, for this I sent a patch via github with the changes that allowed me to compile. In case this is related, I add the details, 
I am using ubuntu 16:

```
gborghesan@kul-XPS-15-9570:~/temp/microblx (master)$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
```

**Comment by kmarkus** [comment]
Hi Gianni

Thanks for reporting, I don't think this issue is related to the compiler. More likely it's a too old version of `lua-unit`. Could you try updating that? You can take a look at the `.travis.yml` file for instructions to manually install a recent version of lua-unit.

**Comment by gborghesan** [comment]
Hello, thanks, solved following your instructions.
```
git clone --depth=1 -b LUAUNIT_V3_3 git://github.com/bluebird75/luaunit
sudo install -Dt /usr/share/lua/5.1/ luaunit/luaunit.lua
```
