### ISSUE TITLE
Has microblx appeared in any papers?

### ISSUE THREAD

**Issue by Pouya-moh** [kmarkus/microblx#28]
Hi Markus,

Hope you're doing fine. I'm Pouya from CMCI (TU Braunschweig). Sorry to write you here but thought would be interesting for future visitors. I was wondering if you have any papers published with microblx. We're writing a paper on some contemporary real-time capable solutions and I wanted to cite your work as one. Let me know if there are any as I failed to fine one.

Bests,
P.

**Comment by kmarkus** [comment]
Hi Pouya,

Cc'ing the mailing list on this valid question.

On Tue, Oct 27, 2020 at 09:31:16AM -0700, Pouya wrote:

>Hope you're doing fine. I'm Pouya from CMCI (TU Braunschweig). Sorry to write
>you here but thought would be interesting for future visitors. I was wondering
>if you have any papers published with microblx. We're writing a paper on some
>contemporary real-time capable solutions and I wanted to cite your work as one.
>Let me know if there are any as I failed to fine one.

You are right, there is not much :-) The one and only is

@InProceedings{  Klotzbuecher2013-RTLWS,
  Author =	 {Klotzb\"{u}cher, Markus and Bruyninckx, Herman},
  title =	 {microblx: a reflective, real-time safe, embedded function block framework},
  institution =  {Department of Mechanical Engineering, Katholieke Universiteit Leuven, Belgium},
  booktitle =	 {Proceedings of the Fifteenth Real-Time Linux Workshop},
  location =	 {Lugano-Manno, Switzerland},
  month =	 {October},
  year =	 2013,
  keywords =	 {real-time, function blocks, software engineering}
}

You are welcome to cite this one.

Thanks,
Markus

-- 
Markus Klotzbuecher
Freelancer Embedded, Distributed & Real-time
Am See 28, 78465 Konstanz, Germany

**Comment by Pouya-moh** [comment]
Great. Thanks and keep up great work!
