### ISSUE TITLE
Scripts can be only executed relative to root folder

### ISSUE THREAD

**Issue by blumenthal** [kmarkus/microblx#3]
Hello Markus,

I noted that the (lua) scripts can be only executed relative to that root folder as (a) the loaded libraries are relative and (b) some other scripts are encoded in a relative manner as well. E.g.

```
ubx.load_module(ni, "std_types/stdtypes/stdtypes.so")
ubx.load_module(ni, "std_types/testtypes/testtypes.so")
```

One possibility to resolve that issue is to use an environment variable that points to the root folder. Something like that:

```
ubx_path = os.getenv("MICROBLX_DIR")  .. "/"

ubx.load_module(ni, ubx_path .. "std_types/stdtypes/stdtypes.so")
ubx.load_module(ni, ubx_path .. "std_types/testtypes/testtypes.so")
```

The variable could be set in the env.sh script which has to be invoke anyway. E.g. by adding this line:

```
export MICROBLX_DIR="$DIR"
```

Sebastian

**Comment by kmarkus** [comment]
Hi Sebastian, for the record: this has been working since v0.3.1.
